version: '3'
services:
  mysql: #Service 1
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      - MYSQL_USER=ma
      - MYSQL_ROOT_PASSWORD=root

  api: #Service 2: Python server
    build:
      context: ./Python-Server
      dockerfile: Dockerfile.dev
    environment:
      - DBUSER=ma
      - DBHOST=mysql
      - DBDATABASE=mysql
      - DBPASSWORD=marbeit
      - DBPORT=3306

  client: #Service 3: React
    stdin_open: true
    build:
      context: ./React-Server
      dockerfile: Dockerfile
    volumes:
      - /home/app/node_modules
      - ./React-Server:/app

  nginx: #Service 4: Loadbalancer
    restart: always
    build:
      context: ./Ngnix
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    depends_on:
      - api
      - client

