#FROM python:3-alpine
FROM python:3.9.2-slim
WORKDIR /home/app/pyServer
COPY requirements.txt .
#RUN apk add --update gcc
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "app.py"]